// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ8cm5mUZg8UBzmJvzK580Bp4GTnyX5rk',
    appId: '1:819422986292:web:3ba6153a7d53f37a30ca61',
    messagingSenderId: '819422986292',
    projectId: 'brasas-54e02',
    authDomain: 'brasas-54e02.firebaseapp.com',
    storageBucket: 'brasas-54e02.appspot.com',
    measurementId: 'G-ZNRH555NX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOkpf8AHVakdXyiwrMPD3FzT0bzhAKRoE',
    appId: '1:819422986292:android:7add5b1d66f6e9ba30ca61',
    messagingSenderId: '819422986292',
    projectId: 'brasas-54e02',
    storageBucket: 'brasas-54e02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWVAkkCbfHpMBfS5Uh6WLmIxmvLEipHv8',
    appId: '1:819422986292:ios:fb06bb8e1763604030ca61',
    messagingSenderId: '819422986292',
    projectId: 'brasas-54e02',
    storageBucket: 'brasas-54e02.appspot.com',
    iosBundleId: 'com.example.appPedidos',
  );
}
